In [4]:
import tensorflow as tf

텐서 = tf.constant(3)
print(텐서)
텐서 = tf.constant([3,4,5])
print(텐서)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [7]:
#텐서 숫자, 리스트를 담는 곳 쓰는 이유 = 행렬의 성질을 이용해 많은 계산을 간편하게 가능

#예시
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])
print(텐서 + 텐서2)

#행렬 표현 -> 2차원 리스트
텐서3 = tf.constant([[1,2]
                    ,[3,4]])

텐서4 = tf.constant([[1,2]
                    ,[3,4]])

print(tf.add(텐서3, 텐서4))
#add,substract,divide,multiply,matmul() 행렬 곱셉 연산

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [9]:
제로 = tf.zeros(10) #0이 10개로 가득찬 텐서 생성
print(제로)
제로행렬 = tf.zeros([2,2])
print(제로행렬)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
